<!--BOOK_INFORMATION-->
*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Reading
Python Programming and Numerical Methods, 
[Chapter 9. Representation of Numbers](https://pythonnumericalmethods.studentorg.berkeley.edu/notebooks/chapter09.00-Representation-of-Numbers.html)

# Problems

## 1. Write a function *my_bin_2_dec(b)*
where *b* is binary number represented by a list of ones and zeros. The last element of *b* represents the coefficient of $2^0$, the second-to-last element of b represents the coefficient of $2^1$, and so on. The output variable, *d*, should be the decimal representation of b. The test cases are provided below. 

In [1]:
def my_bin_2_dec(b):
    Max = len(b)
    d=0
    i = Max-1
    while i >= 0:
        d+=b[i]*2**(Max-1-i)
        i-=1 
    d = int(d)
    return d

In [2]:
# Output: 7
my_bin_2_dec([1,1,1])

7

In [3]:
# Output: 85
my_bin_2_dec([1, 0, 1, 0, 1, 0, 1])

85

In [4]:
# Output: 33554431
my_bin_2_dec([1]*25)

33554431

## 2. Write a function *my_dec_2_bin(d)*
where *d* is a positive integer in decimal, and *b* is the binary representation of *d*. The output *b* must be a list of ones and zeros, and the leading term must be a 1 unless the decimal input value is 0. The test cases are provided below. 

In [5]:
import numpy as np
def my_dec_2_bin(d):
    test=d
    if test == 0:
        i=1    
    else: 
        i=0
    while test > 0:
        test=np.floor(test/2)
        i+=1
    b=np.zeros(i)
    while i > 0:
        b[i-1]=(d%2)
        d=int(d/2)
        i-=1
    return b

In [28]:
# Output: [0]
print(my_dec_2_bin(0))

[0.]


In [7]:
# Output: [1, 0, 1, 1, 1]
print(my_dec_2_bin(23))

[1. 0. 1. 1. 1.]


In [8]:
# Output: [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
print(my_dec_2_bin(2097))

[1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]


## 3. Compute *d = my_bin_2_dec(my_dec_2_bin(12654))*
Use the two functions you wrote in problems 1 and 2. Do you get the same number?

In [9]:
d = my_bin_2_dec(my_dec_2_bin(12654))
print(d)

12654


## 4. Write a function *my_bin_adder(b1,b2)*
where *b1*, *b2* and the output variable *b* are binary numbers represented as in problem 1. The output variable should be computed as *b = b1 + b2*. Do not use your functions from problems 1 and 2 to write this function (i.e., do not convert *b1* and *b2* to decimal; add them, and then convert the result back to binary). This function should be able to accept inputs *b1* and *b2* of any length (i.e., very long binary numbers), and *b1* and *b2* may not necessarily be the same length.

In [10]:
def my_bin_adder(b1, b2):
    w1=len(b1)
    w2=len(b2)
    if w1!=w2:
        if w1>=w2:
            w=w1
            main=b1
        else:
            w=w2
            main=b2
        B=np.zeros(w)
        if w1>=w2:
            for i in range(w2):
                B[i]=b2[i]
        else:
            for i in range(w1):
                B[i]=b1[i]
        B=B[::-1]
        print(B)
        print(main)
    else: 
        main=b1
        w=w1
        B=b2
    Sum=np.zeros(w+1)
    extra = 0
    for i in range(w):
        opt=B[w-i-1] + main[w-1-i] + extra
        if opt == 0:
            Sum[w-i]=0
            extra = 0
        if opt == 1:
            Sum[w-i]=1
            extra = 0
        if opt == 2:
            Sum[w-i]=0
            extra = 1
        if opt == 3:
            Sum[w-i]=1
            extra =1
    if opt == 2 or opt == 3:
        Sum[0]=1
    b=Sum
    return b

In [11]:
# Output: [1, 0, 0, 0, 0, 0]
my_bin_adder([1, 1, 1, 1, 1], [1])

[0. 0. 0. 0. 1.]
[1, 1, 1, 1, 1]


array([1., 0., 0., 0., 0., 0.])

In [12]:
# Output: [1, 1, 1, 0, 0, 1, 1]
my_bin_adder([1, 1, 1, 1, 1], [1, 0, 1, 0, 1, 0, 0])

[0. 0. 1. 1. 1. 1. 1.]
[1, 0, 1, 0, 1, 0, 0]


array([0., 1., 1., 1., 0., 0., 1., 1.])

In [13]:
# Output: [1, 0, 1, 1]
my_bin_adder([1, 1, 0], [1, 0, 1])

array([1., 0., 1., 1.])

## 5. What is the effect of allocating more bits to the fraction versus the characteristic and vice versa? What is the effect of allocating more bits to the sign?

Adding more bits to the fraction will allow for more precise determination of a number. (the value of f+1 can access more values between 1 and 2).

Adding more bits to the characteristic will allow the total range of the number to increase. 

Adding more bits to the sign will do nothing. (at least nothing helpful)

## 6. Write a function *my_ieee_2_dec(ieee)*
where *ieee* is a string contains 64 characters of ones and zeros representing a 64-bit IEEE754 number. The output should be *d*, the equivalent decimal representation of *ieee*. The input variable *ieee* will always be a 64-element string of ones and zeros defining a 64-bit float. 

In [14]:
import decimal
decimal.getcontext().prec=40
def Frac(b):
    Max = len(b)
    d=0
    i = 0
    while i < Max:
        d+=decimal.Decimal(b[i]*2**-(i+1))
        i+=1
    return d
    
def my_ieee_2_dec(ieee):
    ieee=list(ieee)
    Num=0
    e=np.zeros(11)
    f=np.zeros(52)
    if ieee[0]=='1':
        Neg=True
    else:
        Neg=False
    for i in range(11):
        e[i]=ieee[i+1]

    for i in range(52):
        f[i]=ieee[12+i]
    e=my_bin_2_dec(e)
    f=Frac(f)
    d=(2**(e-1023))*(1+f)
    if Neg==True:
        d=-d  
    return d

In [15]:
# Output: -48
ieee = '1100000001001000000000000000000000000000000000000000000000000000'
my_ieee_2_dec(ieee)

Decimal('-48.0')

In [16]:
# Output: 3.39999999999999991118215802999
ieee = '0100000000001011001100110011001100110011001100110011001100110011'
my_ieee_2_dec(ieee)

Decimal('3.399999999999999911182158029987476766110')

## 7. Write a function *my_dec_2_ieee(d)*
where *d* is a number in decimal and output variable *ieee* is a string with 64 characters of ones and zeros representing the 64-bit IEEE754 closest to *d*. You can assume that *d* will not cause an overflow for 64-bit *ieee* numbers.

In [17]:
def my_dec_2_neg(d):
    val=0
    if d == 0:
        return(np.zeros(52))    
    b=np.zeros(52)
    for i in range(52):
        val += 1/(2**(1+i))
        if val <= d:
            b[i]=1
        else:
            val-=1/(2**(1+i))
            b[i]=0

    return b


def my_dec_2_ieee(d):
    ieee=np.zeros(64)
    if d<0:
        ieee[0] = 1
    power=0
    cont=True
    while cont:
        if 2**(power+1)<=abs(d):
            power+=1
        else:
            cont=False
    c=power+1023
    c=my_dec_2_bin(c)
    w=len(c)
    if w!= 11:
        W=11-w
        extra=np.zeros(11)      
        for i in range(w):
            extra[W+i]=c[i]
        c=extra
        
    for i in range(11):
        ieee[i+1]=c[i]

    f=abs(d)/(2**power)-1
    f=my_dec_2_neg(f)

    for i in range(52):
        ieee[12+i]=f[i]
    
    return ieee

my_dec_2_ieee(1.5)

array([0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# Output: '0100000000101110010111101010001110011100001100011010010001101000'
#I am convinced the suggested solution is wrong
d = 1.518484199625
my_dec_2_ieee(d)
my_ieee_2_dec(my_dec_2_ieee(d))

Decimal('1.518484199625000030664523364976048469544')

In [19]:
# Output: '1100000001110011010100100100010010010001001010011000100010010000'

d = -309.141740
my_dec_2_ieee(d)

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.])

In [20]:
# Output: '1100000011011000101010010000000000000000000000000000000000000000'

d = -25252
my_dec_2_ieee(d)

array([1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 8. Define *ieee_baby*
to be a representation of numbers using 6 bits where the first bit is the sign bit, the second and third bits are allocated to the characteristic, and the fourth, fifth, and sixth bits are allocated to the fraction. The normalization for the characteristic is 1.

 - Write all the decimal numbers that can be represented by *ieee_baby*. 
 - What is the largest/smallest gap in *ieee_baby*?

Using two bits 4 values can be set as the characteristic value (0,1,2,3).

Using 3 bits the fractions can be 8 values (0,1,2,3,4,5,6,7).

The sign bit works the same as before

$$n=(-1)^s*2^{e-2}(1-f)$$

In [21]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

def Frac(b):
    Max = len(b)
    d=0
    i = 0
    while i < Max:
        d+=(b[i]*2**-(i+1))
        i+=1
    return d
    
def my_ieee_baby(ieee):
    Num=0
    e=np.zeros(2)
    f=np.zeros(3)
    if ieee[0]==1:
        Neg=True
    else:
        Neg=False
    for i in range(2):
        e[i]=ieee[i+1]

    for i in range(3):
        f[i]=ieee[3+i]
    e=my_bin_2_dec(e)
    f=Frac(f)
    d=(2**(e-2))*(1+f)
    if Neg==True:
        d=-d  
    return d

count =0
array=np.zeros(64)
for z in range(2):
    for y in range(2):
        for x in range(2):
            for i in range(2):
                for j in range(2):
                    for k in range(2):
                        array[count]=my_ieee_baby([z,y,x,i,j,k])
                        count+=1
print("the baby ieee can make ", count, " numbers")

Maxgap=0
Mingap=10
for i in range(63):
    dif=abs(array[i]-array[i+1])
    if dif < Mingap:
        Mingap=dif
    print(dif)
    
values = {'number': array}
dfS = pd.DataFrame(values)
print(dfS)
print("the maximum space betwen values is 0.5 and the miniumum gap between the values is ", Mingap)

the baby ieee can make  64  numbers
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.125
0.125
0.125
0.125
0.125
0.125
0.125
0.125
0.25
0.25
0.25
0.25
0.25
0.25
0.25
4.0
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.03125
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.0625
0.125
0.125
0.125
0.125
0.125
0.125
0.125
0.125
0.25
0.25
0.25
0.25
0.25
0.25
0.25
     number
0   0.25000
1   0.28125
2   0.31250
3   0.34375
4   0.37500
5   0.40625
6   0.43750
7   0.46875
8   0.50000
9   0.56250
10  0.62500
11  0.68750
12  0.75000
13  0.81250
14  0.87500
15  0.93750
16  1.00000
17  1.12500
18  1.25000
19  1.37500
20  1.50000
21  1.62500
22  1.75000
23  1.87500
24  2.00000
25  2.25000
26  2.50000
27  2.75000
28  3.00000
29  3.25000
30  3.50000
31  3.75000
32 -0.25000
33 -0.28125
34 -0.31250
35 -0.34375
36 -0.37500
37 -0.40625
38 -0.43750
39 -0.46875
40 -0.50000
41 -0.56250
42 -0.62500
43 -0.68750
44 -0.75000
45

## 9. Use the *np.spacing* function to determine the smallest number such that the gap is 1.

I don't really understand what this means. What gap?

## 10. What are some of the advantages and disadvantages of using binary versus decimal?

Binary is usful in computation. Because computers work with bits, expressing a number with its binary representaion allows the computer to store and manipulate it. On the other hand decimal is much more effective for humans. Changes between neighboring numbers in decimal make it very easy to interpret a number and quickly understand its value, meanwhile a small change in value of a binary number can cause the string to look significantly different. 

## 11. Write the number 13 (base10) in base1. How would you do addition and multiplication in base1?

$$1111111111111$$
In base 1 integers have no meaning within the string since they all must be the same.
$$111+11111=11111111$$
$$111*11=111111$$

## 12. How high can you count on your fingers if you count in binary?

In [24]:
count =0
for z in range(2):
    for y in range(2):
        for x in range(2):
            for i in range(2):
                for j in range(2):
                    for k in range(2):
                        for q in range(2):
                            for w in range(2):
                                for e in range(2):
                                    for r in range(2):
                                        count+=1

print("I could hypothetically count to ", count, ".")



I could hypothetically count to  1024 .


## 13. Let *b* be a binary number having *n* digits. Can you think of ways to multiply and divide *b* by 2 that does not involve any arithmetic? Hint: Think about how you multiply and divide a decimal number by 10.

In decimal:$$2*2=4$$
In Binary(this is a bad example since this looks like 10^2 in decimal):$$10*10=100$$
Another example:$$20*2=40$$
$$10100*10=101000$$
Therefore, $$b\times2^n=b+{0}$$
and,$$b/2^n=b-{0}$$
I don't know how to properly write this but hopefuly you can understand what I am saying. You would just always add or remove the zero of the far right of the string. (it will always be a 0 if the number is a multiple of 2.)